name: Node CI

on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm test
        env:
          CI: true
